name: Reusable Push to GHCR

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
    secrets:
      APP_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ steps.app-token.outputs.token }}" | docker login ghcr.io -u GITHUB_APP --password-stdin

      - name: Build the Docker image
        run: |  
          cd src 
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.tag }}
          docker tag ghcr.io/${{ github.repository }}:abc1234 ghcr.io/${{ github.repository }}:latest
  
      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         #password: ${{ secrets.GHCR_TOKEN }}
         #password: ${{ secrets.GITHUB_TOKEN }}
         password: ${{ secrets.ORG_GITHUB_TOKEN }}
  
     # Push the Docker image
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.tag }}
          docker push ghcr.io/${{ github.repository }}:latest
