name: Reusable Push to GHCR

on:
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ steps.app-token.outputs.token }}" | docker login ghcr.io -u GITHUB_APP --password-stdin

      # - name: Set Tag
      #   id: tag
      #   run: echo "tag=latest" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:latest
          docker tag ghcr.io/${{ github.repository }}:latest ghcr.io/${{ github.repository }}:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}
          docker push ghcr.io/${{ github.repository }}:latest
